name: pusheos

on: create
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Instalar dependecias
        run: cd my-app; npm install;
      - 
        name: Build el proyecto
        run: cd my-app;npm run build
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          committer: Fabricio Blas <fblas@mobydigital.com>
          fqdn: test-bash.mobydigital.com
          commit_message: Nuevo Push
          build_dir: my-app/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
